### PR TITLE
fix require relative paths

### LINKED ISSUE #3: require relative paths
I'm using atom with [hydrogen plugin](https://github.com/willwhitney/hydrogen), basically is jupyter for the text editor and I have installed your package successfully and everything is working just fine.

screen shot 2015-05-27 at 15 17 20

The problem now is with require for relative paths, which I guess ipython won't know the PATH I'm on and wont pass it to node, does any one know a workaround for this?

```js
var test = require('./test');
```

Error: Cannot find module './test'
at Function.Module._resolveFilename (module.js:336:15)
at Function.Module._load (module.js:278:25)
at Module.require (module.js:365:17)
at require (module.js:384:17)
at Object.Contextify.sandbox.run (/Users/rbarros/package/node_modules/contextify/lib/contextify.js:12:24)
at Context.rawRun (/Users/rbarros/package/build/context.js:105:23)
at Context.rawEvaluate (/Users/rbarros/package/build/context.js:117:23)
at Context.execute (/Users/rbarros/package/build/context.js:194:21)
at Kernel.executeRequest (/Users/rbarros/package/build/kernel.js:153:16)
at Kernel.onShell (/Users/rbarros/package/build/kernel.js:90:14) Runtime error
Cannot find module './test'

### PR DESCRIPTION
**Pull request by ricardofbarros**
This closes #3. Please review it, because I'm not very familiar with ES6.

### CODE REVIEW

**Comment by ricardofbarros** [comment]
Hmm maybe the process.env.PWD isn't the best choice to fix this, I don't know if an exec(pwd) or using a module like execSync would be a overkill or the perfect solution.

**Comment by ricardofbarros** [comment]
And pwd doesn't work cross windows users, but I guess that isn't a major issue, do you know If there's a practical way to see the working directory?

**Comment by jaredly** [comment]
The correct way to get the "working directory" is `process.cwd()`.

However, `path.resolve()` *uses* `process.cwd()`, e.g.

```javascript
process.resolve('.') // -> /current/path
process.resolve('./some-file') // -> /current/path/some-file
process.chdir('/opt')
process.resolve('./awesome') // -> /opt/awesome

**Comment by ricardofbarros** [comment]
Ah I forgot totally of `process.cwd`, nice :+1:

**Comment by ricardofbarros** [comment]
so basically `process.env.PWD` was useless, removed it, and everything is working, even in Atom :smile:

**Comment by jaredly** [comment]
awesome :)

**Pull request merged**
